spring.application.name=payment-service
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}

logging.structured.format.console=ecs
logging.structured.ecs.service.name=${spring.application.name}
logging.structured.ecs.service.environment=${digital-bank.service.runtime-profile:${spring.profiles.active:default}}
logging.structured.json.rename.service=ecs_service
logging.structured.json.rename.correlation_id=ecs_correlation_id
logging.structured.json.rename.traceId=ecs_trace_id
logging.structured.json.rename.spanId=ecs_span_id
logging.structured.json.rename.flat_service=service
logging.structured.json.rename.flat_correlation_id=correlation_id
logging.structured.json.rename.flat_trace_id=trace_id
logging.structured.json.rename.flat_span_id=span_id
logging.structured.json.customizer=com.digitalbank.paymentservice.FlatStructuredLoggingJsonMembersCustomizer

management.tracing.export.zipkin.enabled=${ZIPKIN_TRACING_ENABLED:false}

server.port=${SERVER_PORT:8085}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
