spring.application.name=payment-service
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}

logging.structured.format.console=ecs
logging.structured.ecs.service.name=${spring.application.name}
logging.structured.ecs.service.environment=${digital-bank.service.runtime-profile:${spring.profiles.active:default}}

server.port=${SERVER_PORT:8085}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
